// <auto-generated />
using System;
using ISPSystem.EF.Connections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISPSystem.EF.Migrations
{
    [DbContext(typeof(Connection))]
    [Migration("20210112065953_Alter_Table_Perfil_Solicitacao_AND_Seeds")]
    partial class Alter_Table_Perfil_Solicitacao_AND_Seeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ISPSystem.DomainEntities.Carteira", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Composicao");

                    b.Property<string>("Descricao");

                    b.Property<int>("PerfilID");

                    b.HasKey("ID");

                    b.HasIndex("PerfilID");

                    b.ToTable("Carteira");

                    b.HasData(
                        new { ID = 1, Composicao = "100% Renda Fixa", Descricao = "MAX Renda Fixa", PerfilID = 1 },
                        new { ID = 2, Composicao = "50% Renda Fixa e 50% Renda Variável", Descricao = "MIX Renda Fixa/Renda Variável", PerfilID = 2 },
                        new { ID = 3, Composicao = "100% Renda Variável", Descricao = "MAX Renda Variável", PerfilID = 3 },
                        new { ID = 4, Composicao = "80% Renda Variável e 20% Criptomoeda", Descricao = "MIX Renda Variável/Criptomoeda", PerfilID = 3 }
                    );
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Participante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarteiraID");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.Property<int?>("PerfilID");

                    b.HasKey("ID");

                    b.HasIndex("CarteiraID")
                        .IsUnique()
                        .HasFilter("[CarteiraID] IS NOT NULL");

                    b.HasIndex("PerfilID")
                        .IsUnique()
                        .HasFilter("[PerfilID] IS NOT NULL");

                    b.ToTable("Participante");

                    b.HasData(
                        new { ID = 1, CarteiraID = 1, Idade = 25, Nome = "Maycon Klopper de Carvalho", PerfilID = 1 }
                    );
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Perfil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<int>("Pontuacao");

                    b.HasKey("ID");

                    b.ToTable("Perfil");

                    b.HasData(
                        new { ID = 1, Descricao = "Conservador", Pontuacao = 20 },
                        new { ID = 2, Descricao = "Moderado", Pontuacao = 30 },
                        new { ID = 3, Descricao = "Agressivo", Pontuacao = 40 }
                    );
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Questao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("ID");

                    b.ToTable("Questao");

                    b.HasData(
                        new { ID = 1, Descricao = "Quanto de interesse você tem em investir em renda variável para o longo prazo?" },
                        new { ID = 2, Descricao = "Quanto de interesse você tem em investir em ativos de renda fixa para o longo prazo?" },
                        new { ID = 3, Descricao = "Quanto de interese você tem em investir em títulos públicos para o longo prazo?" },
                        new { ID = 4, Descricao = "Para o longo prazo e sua aposentadoria, você aceitaria o risco maior da renda variável?" },
                        new { ID = 5, Descricao = "Para o longo prazo e sua aposentadoria, você prefere se expor menos a riscos e ficar mais na renda fixa?" }
                    );
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Rentabilidade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano");

                    b.Property<int>("CarteiraID");

                    b.Property<string>("Mes");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("ID");

                    b.HasIndex("CarteiraID");

                    b.ToTable("Rentabilidade");

                    b.HasData(
                        new { ID = 1, Ano = 2020, CarteiraID = 1, Mes = "Janeiro", Porcentagem = -0.05m },
                        new { ID = 2, Ano = 2020, CarteiraID = 1, Mes = "Fevereiro", Porcentagem = -0.07m },
                        new { ID = 3, Ano = 2020, CarteiraID = 1, Mes = "Março", Porcentagem = -0.08m },
                        new { ID = 4, Ano = 2020, CarteiraID = 1, Mes = "Abril", Porcentagem = -0.10m },
                        new { ID = 5, Ano = 2020, CarteiraID = 1, Mes = "Maio", Porcentagem = 0.10m },
                        new { ID = 6, Ano = 2020, CarteiraID = 1, Mes = "Junho", Porcentagem = 0.024m },
                        new { ID = 7, Ano = 2020, CarteiraID = 1, Mes = "Julho", Porcentagem = 0.136m },
                        new { ID = 8, Ano = 2020, CarteiraID = 1, Mes = "Agosto", Porcentagem = -0.035m },
                        new { ID = 9, Ano = 2020, CarteiraID = 1, Mes = "Setembro", Porcentagem = -0.054m },
                        new { ID = 10, Ano = 2020, CarteiraID = 1, Mes = "Outubro", Porcentagem = 0.03m },
                        new { ID = 11, Ano = 2020, CarteiraID = 1, Mes = "Novembro", Porcentagem = 0.07m },
                        new { ID = 12, Ano = 2020, CarteiraID = 1, Mes = "Dezembro", Porcentagem = 0.08m },
                        new { ID = 13, Ano = 2020, CarteiraID = 2, Mes = "Janeiro", Porcentagem = -0.14m },
                        new { ID = 14, Ano = 2020, CarteiraID = 2, Mes = "Fevereiro", Porcentagem = -0.16m },
                        new { ID = 15, Ano = 2020, CarteiraID = 2, Mes = "Março", Porcentagem = -0.086m },
                        new { ID = 16, Ano = 2020, CarteiraID = 2, Mes = "Abril", Porcentagem = -0.102m },
                        new { ID = 17, Ano = 2020, CarteiraID = 2, Mes = "Maio", Porcentagem = 0.02m },
                        new { ID = 18, Ano = 2020, CarteiraID = 2, Mes = "Junho", Porcentagem = 0.038m },
                        new { ID = 19, Ano = 2020, CarteiraID = 2, Mes = "Julho", Porcentagem = 0.266m },
                        new { ID = 20, Ano = 2020, CarteiraID = 2, Mes = "Agosto", Porcentagem = -0.065m },
                        new { ID = 21, Ano = 2020, CarteiraID = 2, Mes = "Setembro", Porcentagem = -0.084m },
                        new { ID = 22, Ano = 2020, CarteiraID = 2, Mes = "Outubro", Porcentagem = 0.06m },
                        new { ID = 23, Ano = 2020, CarteiraID = 2, Mes = "Novembro", Porcentagem = 0.16m },
                        new { ID = 24, Ano = 2020, CarteiraID = 2, Mes = "Dezembro", Porcentagem = 0.145m }
                    );
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Solicitacao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarteiraID");

                    b.Property<string>("Descricao");

                    b.Property<int>("ParticipanteID");

                    b.Property<int>("PerfilID");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("ParticipanteID");

                    b.ToTable("Solicitacao");
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Carteira", b =>
                {
                    b.HasOne("ISPSystem.DomainEntities.Perfil", "Perfil")
                        .WithMany("Carteiras")
                        .HasForeignKey("PerfilID")
                        .HasConstraintName("FK_Carteira_Perfil")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Participante", b =>
                {
                    b.HasOne("ISPSystem.DomainEntities.Carteira", "Carteira")
                        .WithOne("Participante")
                        .HasForeignKey("ISPSystem.DomainEntities.Participante", "CarteiraID")
                        .HasConstraintName("FK_Participante_Carteira");

                    b.HasOne("ISPSystem.DomainEntities.Perfil", "Perfil")
                        .WithOne("Participante")
                        .HasForeignKey("ISPSystem.DomainEntities.Participante", "PerfilID")
                        .HasConstraintName("FK_Participante_Perfil");
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Rentabilidade", b =>
                {
                    b.HasOne("ISPSystem.DomainEntities.Carteira", "Carteira")
                        .WithMany("Rentabilidades")
                        .HasForeignKey("CarteiraID")
                        .HasConstraintName("FK_Rentabilidade_Carteira")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISPSystem.DomainEntities.Solicitacao", b =>
                {
                    b.HasOne("ISPSystem.DomainEntities.Participante", "Participante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("ParticipanteID")
                        .HasConstraintName("FK_Solicitacao_Participante")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
